name: Docker Workflow

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        path: .

    - name: Build Docker Image
      run: |
        cd docker
        ls
        docker build -t docker-imagen .
        docker save docker-imagen | gzip > docker-imagen.tar.gz
        pwd
        ls
        
    - name: Copy Files
      uses: appleboy/scp-action@master
      with:
        host: 161.35.26.40
        username: voltodocker
        key: ${{ env.SSH_KNOWN_HOSTS }}
        source: /home/runner/work/Docker-plone-probak/Docker-plone-probak/docker/docker-imagen.tar.gz
        target: /home/csmant/docker-imagen.tar.gz

    - name: Activate Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: 161.35.26.40
        username: voltodocker
        key: ${{ env.SSH_KNOWN_HOSTS }}
        script: |
          docker stop $(docker ps -aq)
          docker load < docker-imagen.tar.gz
          docker run docker-imagen
