name: Docker Workflow

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        path: .

    - name: Build Docker Image
      run: |
        cd docker
        ls
        docker build -t docker-imagen .
        docker save docker-imagen | gzip > docker-imagen.tar.gz
        pwd
        ls
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add temporary SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: temp_ssh_key
        known_hosts: ${{ secrets.KNOWN_HOSTS }}



    - name: Configure NPM and Yarn authentication
      run: |
        echo "//${{ secrets.CODESYNTAX_NPM_REPO_URL }}:_authToken=${{ secrets.CODESYNTAX_REPO_NPM_TOKEN }}" > ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
        echo "registry \"https://${{ secrets.CODESYNTAX_NPM_REPO_URL }}\"" > ~/.yarnrc


    - name: Run whoami
      run: ssh csmant@161.35.26.40 'whoami'
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  
    - name: Copy Files
      uses: appleboy/scp-action@master
      with:
        host: 161.35.26.40
        username: csmant
        key: ${{ secrets.SSH_KNOWN_HOSTS }}
        script: |
          whoami  
        source: /home/runner/work/Docker-plone-probak/Docker-plone-probak/docker/docker-imagen.tar.gz
        target: /home/csmant/docker-imagen.tar.gz

    - name: Activate Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: 161.35.26.40
        username: csmant
        key: ${{ secrets.SSH_KNOWN_HOSTS }}
        script: |
          docker stop $(docker ps -aq)
          docker load < docker-imagen.tar.gz
          docker run docker-imagen
